# Generated by Django 3.0.4 on 2020-05-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='flag',
            field=models.IntegerField(default=0, verbose_name='成绩类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'general'), ('3', 'difficult'), ('1', 'easy')], max_length=10, null=True, verbose_name='等级'),
        ),
    ]
