# Generated by Django 3.0.4 on 2020-03-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='dept',
            new_name='sdept',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='id',
            new_name='sid',
        ),
    ]
