# Generated by Django 3.0.4 on 2020-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200322_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sdept',
            field=models.CharField(choices=[('计算机科学与技术学院', '计算机科学与技术学院'), ('电气与自动化学院', '电气与自动化学院'), ('外国语学院', '外国语学院'), ('理学院', '理学院')], max_length=20, null=True, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sdept',
            field=models.CharField(choices=[('计算机科学与技术学院', '计算机科学与技术学院'), ('电气与自动化学院', '电气与自动化学院'), ('外国语学院', '外国语学院'), ('理学院', '理学院')], max_length=20, null=True, verbose_name='学院'),
        ),
    ]
